name: Deploy PHP site to Apache server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.SSH_PORT }} "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

    - name: Rsync files to server
      run: |
        rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" --delete \
          --exclude=".git*" \
          --exclude="*.md" \
          ./ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.TARGET_PATH || '/var/www/html' }}

    - name: Restart Apache
      run: |
        ssh -tt -p ${{ secrets.SSH_PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "sudo systemctl restart apache2"
